name: Validate Packer Configuration and Create webapp.zip

on:
  pull_request:
    paths:
      - 'packer/**'

jobs:
  validate-packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update -y
        sudo apt-get install packer -y
        packer --version

    - name: Validate Packer Configuration
      run: |
        cd packer
        packer validate amazon-machine-image.pkr.hcl

    - name: Create webapp.zip
      run: |
        cd ..
        zip -r packer/webapp.zip webapp/*
