name: Validate Packer Configuration and Create webapp.zip

on:
  push:
    paths:
      - 'packer/**'

jobs:
  validate-packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packer
      run: |
        curl -fsSL https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip -o packer.zip
        unzip packer.zip
        chmod +x packer
        mv packer /usr/local/bin/
        packer --version

    - name: Validate Packer Configuration
      run: |
        cd packer
        packer validate amazon-machine-image.pkr.hcl

    - name: Create webapp.zip
      run: |
        cd ..
        zip -r packer/webapp.zip webapp/*

