name: Continuous Integration - Packer Validation
'on':
  push:
    branches:
      - main
env:
  KEY_ID: '${{ secrets.KEY_ID }}'
  SECRET_KEY: '${{ secrets.SECRET_KEY }}'
  AWS_REGION: '${{ secrets.AWS_REGION }}'
  SOURCE_AMI: '${{ secrets.SOURCE_AMI }}'
  ARTIFACT_NAME: ./packer/webapp.zip
jobs:
  build:
    name: Validating Packer
    runs-on: ubuntu-latest
    steps:
      - name: Git Repo
        uses: actions/checkout@v2
      - name: Zip Repo
        uses: montudor/action-zip@v1
        with:
          args: zip webapp.zip .
          source: .
          destination: .
      - name: Validation
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: amazon-machine-image.pkr.hcl
          working_directory: ./packer/
